hedgedoc/hedgedoc.github.io

config.toml

This patch should avoid the usage of brand terminology for general concepts. ("Kleenex"/"Tempo" vs tissue)

Replace GitHub with Source Code

---

themes/vex-hugo/layouts/partials/head.html

This PR adds adds a google site verification token, so we can access the google webmaster tools and see how google indexes  the page. This does NOT add any kind of tracking, google analytics or other metrics. This won't change anything for the users. This is only to control how the google crawler interacts with our page.

Add google site verification to head

---

themes/vex-hugo/layouts/partials/head.html

This PR added the mastodon me-link for verification of our homepage link on the profile. The google-webmasters-verification id is also moved into a new verifications section in the head.
Closes #22

Added mastodon verification link

---

themes/vex-hugo/assets/scss/history.scss

On some display resolutions the history graphs seems to be broken. This PR adds a css fix for this.

Fix min height of history split elements

---

content/english/history.html

This PR changes the history entry for november and adds a history entry for december. November is changed to "release candidate" and december is about the release.

Change november to december

---

content/english/faq.md

This PR adds an explanation about the `X-Frame-Options` header and how it relates to PDF embedding.

Explain `X-Frame-Options` for PDF embedding

---

layouts/shortcodes/faq-entry.html

This PR changes the faq-entry to honor the hugo parameter to show drafts

draft faq-entry are now shown if requested

---

.github/workflows/deploy.yml

This PR adds a new trigger to the `deploy` action so it can be triggered manually.

Add button for manual deployment

---

.github/workflows/reuse.yml

The "Pull Request" trigger in reuse.yml is unnecessary. The check is already covered by "push"

Remove unnecessary trigger

---

data/en/homepage.yml

This PR replaces the "getting started" link with a useful one until our docs page is ready.

Replace getting started link with a working one

---

assets/scss/additional-theme.scss
github-releases.ts
layouts/releases/single.html

This PR adds the docker tags matching each version to their release page.
Closes #56

Added docker tags to release page

---

content/english/_index.html

This PR changes the link to the setup documentation. 
https://github.com/hedgedoc/hedgedoc/pull/741 is needed for this.

Fix setup index link

---

content/english/_index.html

This PR fixes the "Getting Started" Link on the main page.

Replace URL of "getting started" Link on the main page

---

.github/workflows/link-check.yml

This PR adds a GitHub CI job checking for broken links. It is based on the [broken-link-checker npm package](https://www.npmjs.com/package/broken-link-checker). The check runs on pushes to the repo as well as daily scheduled.
Avoiding further unnoticed broken links as reported with #77

Add CI checker for broken links

---

content/english/history.html

This PR fixes the grammar of "re-license" on the history page.

Fix grammar of re-license in history.

---

renovate.json

This PR changes the renovate config. It...
- Activates the weekly yarn.lock maintenance
- Removes the hourly PR limit
- Activate version pinning.

Change renovate config

---

renovate.json

This PR sets the renovate schedule to hourly and activates the dependency dashboard.

Set renovate schedule to hourly and activate dependency dashboard

---

.github/workflows/deploy.yml

This PR pins hugo to 0.83.1.
Hugo 0.84.0 has a bug where menus with custom entries won't get rendered. See https://github.com/gohugoio/hugo/issues/8672

Rollback to hugo 0.83.1

---

renovate.json

The renovate config contains a typo. This PR should correct it.
see https://docs.renovatebot.com/configuration-options/#extractversiontemplate

Correct "extractVersionTemplate" in renovate.config

---

.github/workflows/deploy.yml

Renovate config
Replaces the single quotes in the hugo version in the deploy job with double quotes.

Change single quotes to double quotes in hugo version

---

layouts/releases/list.html
layouts/releases/single.html

This PR adds the date of a release to the release index and details page and also the "latest release" badge to the index page.
Fixes #122

Add more release information

---

content/english/history.html

This PR changes the predicted release date for HedgeDoc 2 to "hopefully 2021" instead of "2021".
We don't know if we can make it this year. Therefore I think we should communicate it like this on the website.

Change the release date for HedgeDoc 2.0 to "hopefully 2021"

---

content/english/history.html

This PR changes the release date of hedgedoc 2 to 2022.

Change release date of hedgedoc 2 to 2022

---

content/english/privacy-policy.md

This PR adds netlify to the privacy policy because the frontend demo is hosted there.

Add netlify to privacy policy

---

.gitignore

This PR adds `.hugo_build.lock` to .gitignore

chore: added .hugo_build.lock to .gitignore

---

.reuse/dep5
.run/start.run.xml
package.json

This PR adds a hugo server run config for WebStorm.

chore: add hugo server run config for WebStorm

---

layouts/history/list.html

This PR fixes the layout of `/history`

Fix layout of history page

---

layouts/partials/head.html

This patch updates the link to the new mastodon account, and thereby providing the correct verification link.

fix: Outdated link to Mastodon account

---

layouts/releases/single.html

This PR removes the sizes of the docker images.

fix(releases): remove size

---

content/english/history/_index.html

This PR changes the release date of HedgeDoc 2 because we haven't released it in 2022.

fix: change release date of hedgedoc 2

---

package.json

This PR fixes the `yarn install` run by calling `node` directly with the `ts-node/esm` loader instead of using the `ts-node-esm` binary which is not compatible with current node anymore.
none

fix: ts-node-esm not running the github-releases util

---

content/english/history/_index.html

This PR adjusts the tentative release of v2 from 2023 to 2024

Adjust tentative release of v2 to 2024
